clickhouse:
  clickhouse:
    image:
      repository: yandex/clickhouse-server
      tag: latest
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  replicas: 1
  type: ClusterIP
kubernetesClusterDomain: cluster.local
pvc:
  data:
    storageRequest: 10Gi
