apiVersion: v1
kind: Service
metadata:
  name: {{ include "datazip.fullname" . }}-clickhouse
  labels:
  {{- include "datazip.labels" . | nindent 4 }}
spec:
  type: {{ .Values.clickhouse.type }}
  selector:
    app: clickhouse
  {{- include "datazip.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.clickhouse.ports | toYaml | nindent 2 }}