apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "datazip.fullname" . }}-data
  labels:
  {{- include "datazip.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.data.storageRequest | quote }}